const lessons = {
  prepare: { label:'Prepare · 8 minutes', title:'Set up your next mix', intro:'Pick two tracks that feel good together. You are preparing the transition before you ever press Play.', tasks:['Load a track on each deck.','Set one memory cue at the start of each track.','Set a hot cue for the vocal or energy change.'] },
  listen: { label:'Listen · 10 minutes', title:'Cue the incoming track', intro:'Learn to hear the next track before the room does.', tasks:['Press headphone cue for the incoming deck.','Use master cue to compare it with the playing track.','Count the next 8-bar phrase in both tracks.'] },
  beatmatch: { label:'Mix · 12 minutes', title:'Beatmatch with tempo', intro:'Match the BPM by ear. Use the tempo slider, then tiny jog nudges to hold the beats together.', tasks:['Start Deck A and count one phrase.','Cue Deck B in your headphones.','Move Deck B tempo until the beats stop drifting.','Use gentle nudges to correct the last drift.'] },
  perform: { label:'Perform · 15 minutes', title:'Make a clean transition', intro:'Bring the next song in with intention. Effects are optional—the timing is what makes it work.', tasks:['Start the incoming song on the first beat of a phrase.','Bring in the channel volume slowly.','Trade low EQ between the two tracks.','Complete the transition and listen back.'] },
};
const setupSteps = ['Choose your controller model or choose Touch only.','Find Deck 1 Play, then press it once.','Find Deck 1 Cue, then press it once.','Find Browse and Load.','Find both tempo controls.','Find headphone cue, master cue, two channel faders, and crossfader.'];
let currentLesson = 'beatmatch', remaining = 720, clock, provider, account, setupIndex = 0;
const done = new Set(JSON.parse(localStorage.getItem('cuecraft-completed') || localStorage.getItem('z2h-completed') || '[]'));
const $ = (id) => document.getElementById(id);
function show(view) { const views={home:$('home'),lesson:$('lesson-view'),setup:$('setup-view')}; Object.entries(views).forEach(([name,element])=>element.hidden=name!==view); window.scrollTo({ top:0, behavior:'smooth' }); }
function updateProgress() { $('progress-summary').textContent = `${done.size} challenge${done.size === 1 ? '' : 's'} complete`; }
function renderLesson(key) { currentLesson=key; const item=lessons[key]; $('lesson-label').textContent=item.label; $('lesson-title').textContent=item.title; $('lesson-instruction').textContent=item.intro; $('task-list').innerHTML=item.tasks.map((task)=>`<li>${task}</li>`).join(''); remaining=key==='perform'?900:key==='beatmatch'?720:key==='listen'?600:480; clearInterval(clock); $('timer').textContent=formatTime(remaining); $('timer-button').textContent='Start timer'; $('task-complete').checked=done.has(key); $('complete-button').disabled=done.has(key); $('completion-note').textContent=done.has(key)?'Completed. Your DJ Passport has been updated.': account?'Practice completion is ready to save. NIM rewards will be claimable from the funded reward pool.':'Connect a wallet to claim NIM rewards. Your progress is always saved on this device.'; show('lesson'); }
function formatTime(seconds) { return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`; }
function renderSetup() { $('setup-step').innerHTML=`<p class="eyebrow teal">Step ${setupIndex + 1} of ${setupSteps.length}</p><h2>${setupSteps[setupIndex]}</h2><p class="muted">You only need the basics to start learning. Skip anything your controller does not have.</p>`; $('setup-next').textContent=setupIndex===setupSteps.length-1?'Finish setup':'I found it'; }
async function connectWallet() { const button=$('wallet-button'); button.disabled=true; button.textContent='Connecting…'; try { const { init } = await import('https://esm.sh/@nimiq/mini-app-sdk'); provider = await init({ timeout:10000 }); const result = await provider.listAccounts(); if (!Array.isArray(result) || !result[0]) throw new Error('No Nimiq account available.'); account=result[0]; $('wallet-status').textContent=`Connected · ${account.slice(0,7)}…${account.slice(-5)}`; button.textContent='Connected'; $('sync-button').disabled=false; } catch (error) { $('wallet-status').textContent='Open this in Nimiq Pay to connect'; button.disabled=false; button.textContent='Try again'; } }
function answerQuestion() { const question=$('coach-input').value.trim().toLowerCase(); if(!question) return; let reply='Stay with one small step: listen, adjust, then listen again.'; if(question.includes('tempo')||question.includes('fast')||question.includes('slow')) reply='If Deck B is pulling ahead, slow it down a tiny bit. If it is falling behind, speed it up a tiny bit. Then use a short nudge—not a big correction—to line up the beats.'; else if(question.includes('cue')||question.includes('headphone')) reply='Use headphone cue to hear the incoming track privately. Keep the master cue available so you can compare it against the song the room is hearing.'; else if(question.includes('beat')||question.includes('count')) reply='Listen for the kick drum. Count groups of four beats, then groups of eight bars. Start your next track on the first beat of a new phrase.'; else if(question.includes('crossfader')||question.includes('fader')) reply='Start with both channel faders as your main volume control. The crossfader is optional for this lesson; keep it centered until the basic transition feels easy.'; $('coach-response').textContent=reply; $('coach-input').value=''; }
async function refreshBridge() { try { const response=await fetch('/api/status',{cache:'no-store'}); if(!response.ok) throw new Error('No local bridge'); const state=await response.json(); const profile=state.profile_name ? ` · ${state.profile_name}` : ''; if(!state.running){$('bridge-status').textContent=`RekordBridge is open${profile}. Choose Test input or Start bridge to connect the controller.`; return;} const mode=state.forwarding?'Rekordbox bridge running':'Controller test mode'; $('bridge-status').textContent=`${mode}${profile}. ${state.device_name || 'Controller'} is connected.`; if(state.last_action){const deck=state.last_action.deck ? ` · Deck ${state.last_action.deck}` : ''; $('control-feedback').textContent=`Controller: ${state.last_action.action.replaceAll('_',' ')}${deck}`;}} catch (_error) {} }
$('wallet-button').addEventListener('click',connectWallet); $('sync-button').addEventListener('click',()=>{ $('completion-note').textContent=`${done.size} completed challenge${done.size===1?'':'s'} synced to your CueCraft progress. NIM claim is ready when the funded reward pool is connected.`; }); $('start-practice').addEventListener('click',()=>renderLesson('beatmatch')); document.querySelectorAll('.launch-lesson').forEach((button)=>button.addEventListener('click',()=>renderLesson(button.dataset.lesson))); $('leave-lesson').addEventListener('click',()=>show('home')); $('setup-button').addEventListener('click',()=>{setupIndex=0;renderSetup();show('setup')}); $('leave-setup').addEventListener('click',()=>show('home')); $('setup-next').addEventListener('click',()=>{ if(setupIndex<setupSteps.length-1){setupIndex++;renderSetup()}else show('home') }); $('coach-send').addEventListener('click',answerQuestion); $('coach-input').addEventListener('keydown',(event)=>{if(event.key==='Enter')answerQuestion()});
refreshBridge(); setInterval(refreshBridge, 1500);
$('timer-button').addEventListener('click',()=>{ if(clock){clearInterval(clock);clock=null;$('timer-button').textContent='Continue timer';return;} $('timer-button').textContent='Pause timer';clock=setInterval(()=>{remaining=Math.max(0,remaining-1);$('timer').textContent=formatTime(remaining);if(!remaining){clearInterval(clock);clock=null;$('timer-button').textContent='Done';$('task-complete').checked=true;$('complete-button').disabled=false;}},1000); });
$('task-complete').addEventListener('change',(event)=>$('complete-button').disabled=!event.target.checked); $('complete-button').addEventListener('click',()=>{done.add(currentLesson);localStorage.setItem('cuecraft-completed',JSON.stringify([...done]));updateProgress();$('complete-button').disabled=true;$('completion-note').textContent=account?'Challenge saved. Your NIM reward is marked claimable when the reward pool is live.':'Challenge saved. Connect your Nimiq wallet later to see any available NIM reward.';}); document.querySelectorAll('[data-control]').forEach((button)=>button.addEventListener('click',()=>{$('control-feedback').textContent=`${button.dataset.control} used — nice. Keep listening for the beat.`;})); updateProgress();
